//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studentmanagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registrartion
    {
        public int Id { get; set; }
        public string FisrtName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public int Courseid { get; set; }
        public int Batchid { get; set; }
        public int PhoneNumber { get; set; }
    }
}
